package io.github.sourcem7.alfajralarm.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/* Expanded pre-dawn palettes. All roles are populated so components can use
 * proper M3 tonal pairings (onX on X, containers, outline-variant dividers,
 * inverse roles for snackbars) in both static and dynamic schemes. */

internal val DawnDark = darkColorScheme(
    primary = Color(0xFFFFC68A),
    onPrimary = Color(0xFF402000),
    primaryContainer = Color(0xFF613D15),
    onPrimaryContainer = Color(0xFFFFDDB9),
    secondary = Color(0xFFAEC8E8),
    onSecondary = Color(0xFF12293F),
    secondaryContainer = Color(0xFF3A4A63),
    onSecondaryContainer = Color(0xFFD3E4FF),
    tertiary = Color(0xFFCDBCF2),
    onTertiary = Color(0xFF33275E),
    tertiaryContainer = Color(0xFF4A3F75),
    onTertiaryContainer = Color(0xFFE6DEFF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF10151D),
    onBackground = Color(0xFFE1E8F2),
    surface = Color(0xFF171E28),
    onSurface = Color(0xFFE1E8F2),
    surfaceVariant = Color(0xFF283340),
    onSurfaceVariant = Color(0xFFB9C4D3),
    surfaceTint = Color(0xFFFFC68A),
    inverseSurface = Color(0xFFE1E8F2),
    inverseOnSurface = Color(0xFF1A2029),
    inversePrimary = Color(0xFF825300),
    surfaceDim = Color(0xFF10151D),
    surfaceBright = Color(0xFF3A4453),
    surfaceContainerLowest = Color(0xFF0B0F15),
    surfaceContainerLow = Color(0xFF151C26),
    surfaceContainer = Color(0xFF1B232F),
    surfaceContainerHigh = Color(0xFF232D3B),
    surfaceContainerHighest = Color(0xFF2E3948),
    outline = Color(0xFF8A94A6),
    outlineVariant = Color(0xFF3A4453),
    scrim = Color.Black,
)

internal val DawnLight = lightColorScheme(
    primary = Color(0xFF825300),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFDDB9),
    onPrimaryContainer = Color(0xFF291800),
    secondary = Color(0xFF365F87),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFD4E4F5),
    onSecondaryContainer = Color(0xFF0C1D2E),
    tertiary = Color(0xFF5B579B),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFE3DFFF),
    onTertiaryContainer = Color(0xFF14124F),
    error = Color(0xFFBA1A1A),
    onError = Color.White,
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF9F9FF),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFF9F9FF),
    onSurface = Color(0xFF191C20),
    surfaceVariant = Color(0xFFDFE7F2),
    onSurfaceVariant = Color(0xFF41474D),
    surfaceTint = Color(0xFF825300),
    inverseSurface = Color(0xFF2E333B),
    inverseOnSurface = Color(0xFFEFF1F6),
    inversePrimary = Color(0xFFFFC68A),
    surfaceDim = Color(0xFFD9DDE4),
    surfaceBright = Color(0xFFF9F9FF),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFF1F3F9),
    surfaceContainer = Color(0xFFECEFF5),
    surfaceContainerHigh = Color(0xFFE6EAF1),
    surfaceContainerHighest = Color(0xFFE0E5EC),
    outline = Color(0xFF757D8C),
    outlineVariant = Color(0xFFC3C9D5),
    scrim = Color.Black,
)
