package io.github.sourcem7.alfajralarm.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/* Refined dawn-inspired greenish palettes. Designed strictly according to
 * Material Design 3 color roles and tonal pairing specifications (onX on X,
 * distinct container levels, outline-variant dividers, inverse roles).
 * Inspired by the peaceful green twilight and dawn of Fajr. */

internal val DawnDark = darkColorScheme(
    primary = Color(0xFF8BD6A3),
    onPrimary = Color(0xFF00391F),
    primaryContainer = Color(0xFF00522F),
    onPrimaryContainer = Color(0xFFA6F3BE),
    secondary = Color(0xFFB6CCB9),
    onSecondary = Color(0xFF223527),
    secondaryContainer = Color(0xFF384B3D),
    onSecondaryContainer = Color(0xFFD2E8D4),
    tertiary = Color(0xFFA2CEDD),
    onTertiary = Color(0xFF033642),
    tertiaryContainer = Color(0xFF224D58),
    onTertiaryContainer = Color(0xFFBEEAF6),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F1511),
    onBackground = Color(0xFFDFE4DD),
    surface = Color(0xFF0F1511),
    onSurface = Color(0xFFDFE4DD),
    surfaceVariant = Color(0xFF414942),
    onSurfaceVariant = Color(0xFFC1C9BF),
    surfaceTint = Color(0xFF8BD6A3),
    inverseSurface = Color(0xFFDFE4DD),
    inverseOnSurface = Color(0xFF2D322D),
    inversePrimary = Color(0xFF15653C),
    surfaceDim = Color(0xFF0F1511),
    surfaceBright = Color(0xFF353B36),
    surfaceContainerLowest = Color(0xFF0A0F0C),
    surfaceContainerLow = Color(0xFF171D19),
    surfaceContainer = Color(0xFF1B211D),
    surfaceContainerHigh = Color(0xFF252C27),
    surfaceContainerHighest = Color(0xFF303732),
    outline = Color(0xFF8B938A),
    outlineVariant = Color(0xFF414942),
    scrim = Color.Black,
)

internal val DawnLight = lightColorScheme(
    primary = Color(0xFF15653C),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFA6F3BE),
    onPrimaryContainer = Color(0xFF00210F),
    secondary = Color(0xFF4F6353),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFD2E8D4),
    onSecondaryContainer = Color(0xFF0D1F13),
    tertiary = Color(0xFF3B656F),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFBEEAF6),
    onTertiaryContainer = Color(0xFF001F26),
    error = Color(0xFFBA1A1A),
    onError = Color.White,
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF7FAF4),
    onBackground = Color(0xFF181D19),
    surface = Color(0xFFF7FAF4),
    onSurface = Color(0xFF181D19),
    surfaceVariant = Color(0xFFDDE5DC),
    onSurfaceVariant = Color(0xFF414942),
    surfaceTint = Color(0xFF15653C),
    inverseSurface = Color(0xFF2D322D),
    inverseOnSurface = Color(0xFFEEF2EB),
    inversePrimary = Color(0xFF8BD6A3),
    surfaceDim = Color(0xFFD7DBD4),
    surfaceBright = Color(0xFFF7FAF4),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFF1F5EE),
    surfaceContainer = Color(0xFFEBEFE8),
    surfaceContainerHigh = Color(0xFFE5EAE2),
    surfaceContainerHighest = Color(0xFFDFE4DD),
    outline = Color(0xFF717971),
    outlineVariant = Color(0xFFC1C9BF),
    scrim = Color.Black,
)
